import { Router } from "express";
import type { IRouter } from "express";
import { db, backlinksTable, clientsTable } from "@workspace/db";
import { eq, sql } from "drizzle-orm";
import { requireAuth } from "../lib/auth";
import {
  ListBacklinksQueryParams,
  ListBacklinksResponse,
  CreateBacklinkBody,
  BulkCreateBacklinksBody,
  GetBacklinksChartQueryParams,
  GetBacklinksChartResponse,
  GetDisavowListQueryParams,
  GetDisavowListResponse,
  UpdateBacklinkParams,
  UpdateBacklinkBody,
  UpdateBacklinkResponse,
  DeleteBacklinkParams,
} from "@workspace/api-zod";

const router: IRouter = Router();

function parseId(raw: unknown): number {
  const r = Array.isArray(raw) ? raw[0] : raw;
  return parseInt(r as string, 10);
}

async function formatBacklink(b: typeof backlinksTable.$inferSelect) {
  const [clientRow] = await db.select().from(clientsTable).where(eq(clientsTable.id, b.clientId));
  return {
    ...b,
    clientName: clientRow?.name ?? null,
    firstDetected: b.firstDetected.toISOString(),
    lastSeen: b.lastSeen?.toISOString() ?? null,
  };
}

router.get("/backlinks", requireAuth, async (req, res): Promise<void> => {
  const params = ListBacklinksQueryParams.safeParse(req.query);
  const clientId = params.success ? params.data.clientId : undefined;
  const status = params.success ? params.data.status : undefined;

  let query = db.select().from(backlinksTable).$dynamic();
  if (clientId) query = query.where(eq(backlinksTable.clientId, clientId));
  if (status) query = query.where(eq(backlinksTable.status, status));
  const backlinks = await query.orderBy(sql`${backlinksTable.firstDetected} DESC`);

  res.json(ListBacklinksResponse.parse(await Promise.all(backlinks.map(formatBacklink))));
});

router.post("/backlinks", requireAuth, async (req, res): Promise<void> => {
  const parsed = CreateBacklinkBody.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.message }); return; }
  const [backlink] = await db.insert(backlinksTable).values({
    ...parsed.data,
    isToxic: parsed.data.isToxic ?? false,
    status: parsed.data.status ?? "new",
  }).returning();
  res.status(201).json(await formatBacklink(backlink));
});

router.post("/backlinks/bulk", requireAuth, async (req, res): Promise<void> => {
  const parsed = BulkCreateBacklinksBody.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.message }); return; }
  const inserted = await db.insert(backlinksTable).values(
    parsed.data.backlinks.map((b: typeof parsed.data.backlinks[number]) => ({
      ...b,
      isToxic: b.isToxic ?? false,
      status: b.status ?? "new",
    }))
  ).returning();
  res.status(201).json(await Promise.all(inserted.map(formatBacklink)));
});

router.get("/backlinks/chart", requireAuth, async (req, res): Promise<void> => {
  const params = GetBacklinksChartQueryParams.safeParse(req.query);
  const clientId = params.success ? params.data.clientId : undefined;

  // Parameterized: clientId is bound, never string-interpolated into the SQL.
  const clientFilter = clientId != null ? sql` AND b.client_id = ${clientId}` : sql``;
  const result = await db.execute(sql`
    SELECT
      TO_CHAR(DATE_TRUNC('day', gs.day), 'YYYY-MM-DD') AS date,
      COUNT(CASE WHEN b.status = 'new' THEN 1 END)::int AS "newCount",
      COUNT(CASE WHEN b.status = 'lost' THEN 1 END)::int AS "lostCount"
    FROM GENERATE_SERIES(NOW() - INTERVAL '29 days', NOW(), '1 day'::interval) AS gs(day)
    LEFT JOIN backlinks b ON DATE_TRUNC('day', b.first_detected) = DATE_TRUNC('day', gs.day)${clientFilter}
    GROUP BY gs.day
    ORDER BY gs.day
  `);

  res.json(GetBacklinksChartResponse.parse(result.rows));
});

router.get("/backlinks/disavow", requireAuth, async (req, res): Promise<void> => {
  const params = GetDisavowListQueryParams.safeParse(req.query);
  const clientId = params.success ? params.data.clientId : undefined;

  let query = db.select().from(backlinksTable).where(eq(backlinksTable.isToxic, true)).$dynamic();
  if (clientId) query = query.where(eq(backlinksTable.clientId, clientId));
  const toxic = await query;

  const domains = [...new Set(toxic.map(b => {
    try { return new URL(b.sourceUrl).hostname; } catch { return b.sourceUrl; }
  }))];

  const content = `# Disavow list generated by SEO Admin Panel\n# Date: ${new Date().toISOString()}\n\n${domains.map(d => `domain:${d}`).join("\n")}`;

  res.json(GetDisavowListResponse.parse({ content, count: domains.length }));
});

router.patch("/backlinks/:id", requireAuth, async (req, res): Promise<void> => {
  const params = UpdateBacklinkParams.safeParse(req.params);
  if (!params.success) { res.status(400).json({ error: "Invalid id" }); return; }
  const id = parseId(params.data.id);
  const parsed = UpdateBacklinkBody.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.message }); return; }
  const [backlink] = await db.update(backlinksTable).set(parsed.data).where(eq(backlinksTable.id, id)).returning();
  if (!backlink) { res.status(404).json({ error: "Backlink not found" }); return; }
  res.json(UpdateBacklinkResponse.parse(await formatBacklink(backlink)));
});

router.delete("/backlinks/:id", requireAuth, async (req, res): Promise<void> => {
  const params = DeleteBacklinkParams.safeParse(req.params);
  if (!params.success) { res.status(400).json({ error: "Invalid id" }); return; }
  const id = parseId(params.data.id);
  const [backlink] = await db.delete(backlinksTable).where(eq(backlinksTable.id, id)).returning();
  if (!backlink) { res.status(404).json({ error: "Backlink not found" }); return; }
  res.sendStatus(204);
});

export default router;
